UPDATE entity_names SET RICname='Kamerun & German Togoland' WHERE original_name='kameroen en togo';
UPDATE entity_names SET RICname='Kamerun & German Togoland' WHERE original_name='togo et cameroun';
UPDATE entity_names SET RICname='Kamerun & German Togoland' WHERE original_name='kamerun et togo';
UPDATE entity_names SET RICname='South West Africa (German West Africa) (Namibia) & Kamerun & German Togoland' WHERE original_name='deutsch südwestafrika et kamerun et togo';
UPDATE entity_names SET RICname='German Togoland' WHERE original_name='togo';
UPDATE entity_names SET RICname='German Togoland' WHERE original_name='togoland';
UPDATE entity_names SET RICname='Togo (French Togoland)' WHERE original_name='togo (mandat français)';
UPDATE entity_names SET RICname='Togo (French Togoland)' WHERE original_name='mandatsgebiet togo';
UPDATE entity_names SET RICname='Togo (French Togoland)' WHERE original_name='togoland (france)';
UPDATE entity_names SET RICname='Alhucemas' WHERE original_name='alhucemas';
UPDATE entity_names SET RICname='Bolivia-Peru Confederation' WHERE original_name='pérou et bolivie';
UPDATE entity_names SET RICname='Bolivia-Peru Confederation' WHERE original_name='perou, bolivie';
UPDATE entity_names SET RICname='Bolivia-Peru Confederation' WHERE original_name='peru en bolivia';
UPDATE entity_names SET RICname='Bolivia-Peru Confederation' WHERE original_name='peru and bolivia';
UPDATE entity_names SET RICname='Bolivia-Peru Confederation' WHERE original_name='peru & bolivia';
UPDATE entity_names SET RICname='Australian Northern Territory & South Australia' WHERE original_name='south australia and northern territory';
UPDATE entity_names SET RICname='Australian Northern Territory & South Australia' WHERE original_name='australia : south australia (including northern territory)';
UPDATE entity_names SET RICname='Australian Northern Territory & South Australia' WHERE original_name='australia (south australia including northern territory)';
UPDATE entity_names SET RICname='Australian Northern Territory & South Australia' WHERE original_name='australasia : south australia (including northern territory)';
UPDATE entity_names SET RICname='Ross Dependency' WHERE original_name='ross sea';
UPDATE entity_names SET RICname='United States of Central America' WHERE original_name='central america us territories';
UPDATE entity_names SET RICname='United States of Central America' WHERE original_name='republics of central america';
UPDATE entity_names SET RICname='United States of Central America' WHERE original_name='central republic';
UPDATE entity_names SET RICname='United States of Central America' WHERE original_name='fed. centraal-amerika';
UPDATE entity_names SET RICname='U. S. Pacific Trust Territories' WHERE original_name='japanese pacific mandated territories';
UPDATE entity_names SET RICname='St. Croix & St. John & St. Thomas' WHERE original_name='danish west indies (ste. croix, st. thomas and st. john)';
UPDATE entity_names SET RICname='Saint John River' WHERE original_name='san john river';
UPDATE entity_names SET RICname='Kuria Muria Is.' WHERE original_name='arabia : kooria mooria islands';
UPDATE entity_names SET RICname='Kuria Muria Is.' WHERE original_name='arabia : eooria mooria islands';
UPDATE entity_names SET RICname='Alhucemas' WHERE original_name='alhucemas';
UPDATE entity_names SET RICname='Bolivia-Peru Confederation' WHERE original_name='pérou et bolivie';
UPDATE entity_names SET RICname='Bolivia-Peru Confederation' WHERE original_name='perou, bolivie';
UPDATE entity_names SET RICname='Bolivia-Peru Confederation' WHERE original_name='peru en bolivia';
UPDATE entity_names SET RICname='Bolivia-Peru Confederation' WHERE original_name='peru and bolivia';
UPDATE entity_names SET RICname='Bolivia-Peru Confederation' WHERE original_name='peru & bolivia';
UPDATE entity_names SET RICname='Georgia' WHERE original_name='georgia';
UPDATE entity_names SET RICname='Italian East Africa' WHERE original_name='italienische ostafrika';
UPDATE entity_names SET RICname='Italian East Africa' WHERE original_name='italian east africa';
UPDATE entity_names SET RICname='Italian East Africa' WHERE original_name="côte orientale d'afrique possessions italiennes";
UPDATE entity_names SET RICname='Italian East Africa' WHERE original_name='italian possessions in eastern africa';
UPDATE entity_names SET RICname='Nassau' WHERE original_name='nasau';
UPDATE entity_names SET RICname='Vanuatu (New Hebrides)' WHERE original_name='new hebrides';
UPDATE entity_names SET RICname='Vanuatu (New Hebrides)' WHERE original_name='nouvelles-hébrides';
UPDATE entity_names SET RICname='Vanuatu (New Hebrides)' WHERE original_name='nouvelle-hébrides';
UPDATE entity_names SET RICname='Macedonia Former Yugoslav Republic of' WHERE original_name='turquie (macédoine)';
UPDATE entity_names SET RICname='Iraq (Mesopotamia) & Kuweit' WHERE original_name='irak et koveit';
UPDATE entity_names SET RICname='Iraq (Mesopotamia) & Kuweit' WHERE original_name='irak et koweit';
UPDATE entity_names SET RICname='Iraq (Mesopotamia) & Kuweit' WHERE original_name='iraq and koweit';
UPDATE entity_names SET RICname='Kuweit' WHERE original_name='koweit';
UPDATE entity_names SET RICname='Africa Coast & Algeria & Libya (Tripolitania Cyrenaica Fezzan) & Morocco & Tunisia' WHERE original_name="alger, etats-barbaresques et côte d'afrique";
UPDATE entity_names SET RICname='Africa Coast & Libya (Tripolitania Cyrenaica Fezzan) & Morocco & Tunisia' WHERE original_name="etats-barbaresques et côte d'afrique";
UPDATE entity_names SET RICname='Libya (Tripolitania Cyrenaica Fezzan) & Morocco & Tunisia' WHERE original_name='barbarysche staten';
UPDATE entity_names SET RICname='Libya (Tripolitania Cyrenaica Fezzan) & Morocco & Tunisia' WHERE original_name='états barbaresques';
UPDATE entity_names SET RICname='Libya (Tripolitania Cyrenaica Fezzan) & Morocco & Tunisia' WHERE original_name='barbary states (algeria, tunis &c.)';
UPDATE entity_names SET RICname='Libya (Tripolitania Cyrenaica Fezzan) & Morocco & Tunisia' WHERE original_name='barbary states-algeria, etc.';
UPDATE entity_names SET RICname='Libya (Tripolitania Cyrenaica Fezzan) & Morocco & Tunisia' WHERE original_name='barbary states - algeria, etc';
UPDATE entity_names SET RICname='Libya (Tripolitania Cyrenaica Fezzan) & Morocco & Tunisia' WHERE original_name='barbarie';
UPDATE entity_names SET RICname='Libya (Tripolitania Cyrenaica Fezzan) & Morocco & Tunisia' WHERE original_name='barbarian states';
UPDATE entity_names SET RICname='Libya (Tripolitania Cyrenaica Fezzan) & Morocco & Tunisia' WHERE original_name='etats barbaresques';
UPDATE entity_names SET RICname='Libya (Tripolitania Cyrenaica Fezzan) & Morocco & Tunisia' WHERE original_name='etats barbaresques (régence de tripoli, tunisie et maroc)';
UPDATE entity_names SET RICname='Libya (Tripolitania Cyrenaica Fezzan) & Morocco & Tunisia' WHERE original_name='régence et etats barbaresques';
UPDATE entity_names SET RICname='Libya (Tripolitania Cyrenaica Fezzan) & Morocco' WHERE original_name='régences barbaresques';
UPDATE entity_names SET RICname='Libya (Tripolitania Cyrenaica Fezzan) & Morocco' WHERE original_name='autres etats barbaresques';
UPDATE entity_names SET RICname='Egypt/United Arab Republic & Libya (Tripolitania Cyrenaica Fezzan) & Morocco & Tunisia' WHERE original_name='egypte et régences barbaresques';
UPDATE entity_names SET RICname='Libya (Tripolitania Cyrenaica Fezzan) & Morocco & Tunisia & Turkey' WHERE original_name='turquie et barbarie';
UPDATE entity_names SET RICname='Libya (Tripolitania Cyrenaica Fezzan) & Morocco & Tunisia & Turkey' WHERE original_name='turquie et etats barbaresques';
UPDATE entity_names SET RICname='Selangore' WHERE original_name='selangor';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='guyane holandaise';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='indes occidentales néerlandaises (surinam)';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='surinam';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='surinam (guiana)';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='dutch guiana (holland)';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='guiana (netherlands)';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='guyana (nederlandsch)';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='netherlands guiana';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='guiana (netherland)';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='guayana holandesa';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='dutch guiana (netherlands)';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='guyanna hollandeza';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='suriname';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='guyane néerlandaise';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='guyana (netherlands)';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='dutch guiana';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='guyana holandesa';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='guyane hollandaise';
UPDATE entity_names SET RICname='Suriname' WHERE original_name='guyane pays bas';